set windows-shell := ['pwsh', '-Command']

default: build64 build32 copy

debug: debug64 debug32

debug64:
    cmake -B ../../build/Invisibilis/build64 -A x64 -T ClangCL -DCMAKE_BUILD_TYPE=Debug
    cmake --build ../../build/Invisibilis/build64 --config Debug

debug32:
    cmake -B ../../build/Invisibilis/build32 -A Win32 -T ClangCL -DCMAKE_BUILD_TYPE=Debug
    cmake --build ../../build/Invisibilis/build32 --config Debug

build64:
    cmake -B ../../build/Invisibilis/build64 -A x64 -T ClangCL -DCMAKE_BUILD_TYPE=Release
    cmake --build ../../build/Invisibilis/build64 --config Release

build32:
    cmake -B ../../build/Invisibilis/build32 -A Win32 -T ClangCL -DCMAKE_BUILD_TYPE=Release
    cmake --build ../../build/Invisibilis/build32 --config Release

copy:
    cp ../../build/Invisibilis/Release/*.dll ../../build/Desktop_Qt_6_9_1_llvm_mingw_64_bit-Release
